- platform: rest
  name: PostenDeliveryDays
  resource: https://www.posten.no/levering-av-post-2020/_/component/main/1/leftRegion/1?postCode=3409
  headers:
    x-requested-with: XMLHttpRequest
  scan_interval: 57600
  value_template: "{{ value_json.nextDeliveryDays }}"
